### ISSUE TITLE
New science pack to accommodate modified Drude profiles for PAHs/Dust.

### ISSUE THREAD

**Issue by els1** [PAHFIT/pahfit#205]
Implement modified (highly asymmetric) Drude profiles for fitting and train on PDRs to set constraints on parameters for science pack.

**Comment by jdtsmith** [comment]
I'm going to include a `mod_asym` attribute as an option for dust features.  This will "turn on" the Modified Drude in the science pack.  We do need to figure out what the scale of that is.  Relative to FWHM perhaps?  So a value of 1.5 would mean "extra asymmetry 1.5x FWHM to red side" or similar?

**Comment by karllark** [comment]
Interesting.  

The size of the asymmetry is not easy to translate.

**Comment by jdtsmith** [comment]
@Ameek-Sidhu, how does the asymmetry parameterization look now? I think a "relative to the FWHM" asymmetry could be good.  And if FWHM is allowed to vary, that could be "relative to the _initial_ FWHM".

**Comment by jdtsmith** [comment]
Here's a snippet of the current idea (not for actual use, just an example):


```yaml
# Dust features [attributes: wavelength, power, fwhm, mod_asym]
PAH77:
    kind: dust_feature # Drude profiles
    features:
        PAH77a:
            wavelength: 7.42
            fwhm: 0.935
        PAH77b:
            wavelength: 7.60
            fwhm: 0.3344
        PAH77c:
            wavelength: 7.85
            fwhm:
                value: 0.416
                bounds: [-5%, 15%]
            mod_asym: 0.25 # indicates a modified/enhanced-asymmetry Drude profile.
```
